---
:root: /opt/backline
:root_is_prefix: true
:name: backline
:name_suffix: ruby
:ruby:
  :src: src/ruby-1.9.3-p448
  :version: 1.9.3-p448
:openssl:
  :src: src/openssl-1.0.1g
:zlib:
  :src: src/zlib-1.2.7
:yaml:
  :src: src/yaml-0.1.6
:ffi:
  :src: src/libffi-3.0.11
:autoconf:
  :src: src/autoconf-2.68
