---
:root: /opt/operations
:root_is_prefix: true
:name: operations
:name_suffix: ruby_193p484
:ruby:
  :src: src/ruby-1.9.3-p484
  :version: 1.9.3-p484
:openssl:
  :src: src/openssl-1.0.1f
:zlib:
  :src: src/zlib-1.2.7
:yaml:
  :src: src/yaml-0.1.4
:ffi:
  :src: src/libffi-3.0.11
:autoconf:
  :src: src/autoconf-2.68
